.TH "Ngila" 1
.SH NAME
Ngila \- Logarithmic and Affine Sequence Alignment
.SH SYNOPSIS
.B ngila
\-hnpisvqef \-a <n> \-b <n> \-c <n> \-x <file> \-m <n> \-r <n> file
.SH DESCRIPTION
Ngila is a global, pairwise sequence alignment program that implements the algorithm of 
Miller and Myers (1988), optimized for gap penalty C(x)=a+b*x+c*ln x.
.SH OPTIONS
.TP
.B default
ngila -eipq -a 1.0 -b 1.0 -c 0.0 -m 0.0 -r 1.0
.TP
.B \-a <number>
gap open penalty
.TP
.B \-b <number>
gap extenstion penalty
.TP
.B \-c <number>
logarithmic gap penalty
.TP
.B \-e
score end gaps
.TP
.B \-f
do not score end gaps
.TP
.B \-h
print help message
.TP
.B \-i
case-insensitive sequences
.TP
.B \-m <number>
base match penalty
.TP
.B \-n
negate penalty matrix
.TP
.B \-q
turn messages off
.TP
.B \-p
do not negate penalty matrix
.TP
.B \-r <number>
base mismatch (replacement) penalty
.TP
.B \-s
case-sensitive sequences
.TP
.B \-x <file>
penalty matrix file
.TP
.B \-v
turn messages on
.TP